---
title: "geom2D"
output: html_notebook
---

```{r}
library(magrittr) # pipe: %>%
library(zeallot) # unpacking: %<-% 
library(plot3D)
```



## 2D -> 2D mappings (functions of complex argument)



```{r}
(function(){
  
  # > complexGrid(1:3, (1:3)*1i)
  # [,1] [,2] [,3]
  # [1,] 1+1i 1+2i 1+3i
  # [2,] 2+1i 2+2i 2+3i
  # [3,] 3+1i 3+2i 3+3i
  complexGrid <- function(re, im) outer(re, im, FUN = `+`)
  
  surfToSurf <- function(z) z^2
  
  
  approxLinFunByUnitLen <- function(x,y) {
    ds <- sqrt(diff(x)^2 + diff(y)^2)
    s <- c(0, cumsum(ds))
    xByLength <- approxfun(s, x)
    yByLength <- approxfun(s, y)
    totalLength <- s[length(s)]
    
    xByUnitLength <- function(s) xByLength(s*totalLength)
    yByUnitLength <- function(s) yByLength(s*totalLength)
    
    
    function(s, ds = 0.05) {
      x <- xByUnitLength(s)
      y <- yByUnitLength(s)
      rotRad <- atan((yByUnitLength(s+ds) - y)/(xByUnitLength(s+ds) - x))
      
      list(x=x, y=y, rotRad = rotRad, srt = rotRad * 360 / 2 / pi)
    } 
  }
  
  plotLabelAtLine <- function(x, y, label, boxSizeX, boxSizeY, atUnitLength = 0.5, labelSize = 0.8 ) {
    p <- approxLinFunByUnitLen(x, y)(atUnitLength)
    # print(p$rotRad)
    R <- matrix(c(cos(p$rotRad), sin(p$rotRad), -sin(p$rotRad), cos(p$rotRad)), ncol = 2)
    verts <- rbind(
      c(-boxSizeX, -boxSizeX, boxSizeX, boxSizeX),
      c(-boxSizeY, boxSizeY, boxSizeY, -boxSizeY)
    )
    rotVerts <- R %*% verts
    vX <- rotVerts[1,] + p$x
    vY <- rotVerts[2,] + p$y
    
    polygon(vX, vY, col = "white", border = "transparent")
    text(p$x,p$y, labels = label, srt = p$srt, cex = labelSize)
    
  }
  
  
  plotSurfaceLines <- function(ofMatrix, 
                               withXLines = withYLines, 
                               withYLines = withXLines, 
                               atUnitLength = 0.5) {
    
    rowsIdx <- seq(from = 1, to = nrow(ofMatrix), length.out = withXLines) %>% round
    rows <- ofMatrix[rowsIdx,]
    # rows %>% print
    colsIdx <- seq(from = 1, to = ncol(ofMatrix), length.out = withYLines) %>% round
    cols <- ofMatrix[,colsIdx]
    # cols %>% print
    
    xRange <- range(Re(ofMatrix))
    xRangeDiff <- xRange[2] - xRange[1]
    yRange <- range(Im(ofMatrix))
    yRangeDiff <- yRange[2] - yRange[1]
    p <- plot(
      xRange, # + c(-xRangeDiff/withXLines, xRangeDiff/withXLines), 
      yRange, # + c(-yRangeDiff/withYLines, yRangeDiff/withYLines), 
      type = "n")
    
    # background <- par("bg")
    for(i in 1:nrow(rows)) {
      rowLineRe <- Re(rows[i,])
      rowLineIm <- Im(rows[i,])
      lines(rowLineRe, rowLineIm, type = "l")
      

      
      # rect(xleft = rowLineRe[length(rowLineRe)]-xRangeDiff/withXLines/2,
      #      xright = rowLineRe[length(rowLineRe)]+xRangeDiff/withXLines/2,
      #      ybottom = rowLineIm[length(rowLineIm)] - xRangeDiff/withXLines - xRangeDiff/withXLines/2,
      #      ytop = rowLineIm[length(rowLineIm)] - xRangeDiff/withXLines + xRangeDiff/withXLines/2,
      #      col = "white", border = "transparent")
      # text(rowLineRe[length(rowLineRe)], 
      #      rowLineIm[length(rowLineIm)] - xRangeDiff/withXLines, 
      #      labels = rowLineRe[1],
      #      cex = 0.8)
    }
    for(j in 1:ncol(cols)){
      colLineRe <- Re(cols[,j])
      colLineIm <- Im(cols[,j])
      lines(colLineRe, colLineIm, type = "l")
      
      
      
      
      # rect(xleft = colLineRe[1]-yRangeDiff/withYLines/2,
      #      xright = colLineRe[1]+yRangeDiff/withYLines/2,
      #      ybottom = colLineIm[1] - yRangeDiff/withYLines - yRangeDiff/withYLines/2,
      #      ytop = colLineIm[1] - yRangeDiff/withYLines + yRangeDiff/withYLines/2,
      #      col = "white", border = "transparent")
      # text(colLineRe[1] + yRangeDiff/withYLines, 
      #      colLineIm[1], 
      #      labels = c(paste0("i", colLineIm[1])),
      #      cex = 0.8)
    }
    
    for(i in 1:nrow(rows)) {
      rowLineRe <- Re(rows[i,])
      rowLineIm <- Im(rows[i,])
      
      plotLabelAtLine(rowLineRe, rowLineIm, 
                      label = rowsIdx[i],
                      # label = rowLineRe[1],
                      boxSizeX = xRangeDiff/withXLines/5,
                      boxSizeY = yRangeDiff/withYLines/6,
                      atUnitLength = atUnitLength)
    }
    for(j in 1:ncol(cols)){
      colLineRe <- Re(cols[,j])
      colLineIm <- Im(cols[,j])
      
      plotLabelAtLine(colLineRe, colLineIm, 
                      label = c(paste0("i", colsIdx[j])), 
                      # label = c(paste0("i", colLineIm[1])), 
                      boxSizeX = xRangeDiff/withXLines/5,
                      boxSizeY = yRangeDiff/withYLines/6,
                      atUnitLength = atUnitLength)
    }
    
    p
  }
  
  
  
  
  # mat <- complexGrid(1:6, (1:3)*1i)
  # mat %>% print
  # range(Re(mat)) %>% print
  # range(Im(mat)) %>% print
  # mat[seq.int(from = 1, to = nrow(mat), length.out = 3),] %>%  print
  # mat[,seq.int(from = 1, to = ncol(mat), length.out = 3)] %>%  print
  # mat[1,] %>% print
  # mat[,1] %>% print
  
  plotSurfaceLines(complexGrid(-10:10, (-10:10)*1i), 
                   withXLines = 10, 
                   withYLines = 5, 
                   atUnitLength = 0.9)
  grid()
  plotSurfaceLines(complexGrid(-10:10, (-10:10)*1i)^2, 
                   withXLines = 10, 
                   withYLines = 5, 
                   atUnitLength = 0.9)
  grid()
  contour(Mod(complexGrid(1:20, (1:20)*1i)^2), nlevels = 15)
  grid()
  contour(Mod(complexGrid(1:20, (1:20)*1i)), nlevels = 15)
  grid()
  
  # persp(
  #   Mod(complexGrid(-10:10, (-10:10)*1i)^2), 
  #   theta = 30, phi = 30, expand = 0.5, 
  #   col = "lightblue", ltheta = 120, shade = 0.75, 
  #   ticktype = "detailed",
  #   xlab = "Re", ylab = "Im", zlab = "r^2"
  # )
  
  
  
  
  data <- complexGrid(-10:10, (-10:10)*1i)^2
  dataMod <- Mod(data)
  dataModRange <- range(dataMod)
  
  # persp3D(z = dataMod, col = "white", zlim = dataModRange + c(0, 50),
  #        shade = 0.1, d = 2, plot = FALSE, ticktype = "detailed")
  # contour3D(z = dataMod, colvar = dataMod, lwd = 2, add = TRUE, 
  #        nlevels = 20, clab = c("height", "m"), plot = FALSE, colkey = FALSE
  #        # colkey = list(at = seq(90, 190, length.out = 5))
  #        )
  # contour3D(z = dataModRange[2] + 50, colvar = dataMod, lwd = 2, col = "grey",
  #        add = TRUE, nlevels = 5, colkey = FALSE)
  # contour3D(z = dataModRange[1], colvar = dataMod, lwd = 2, col = "black",
  #        add = TRUE, nlevels = 5, colkey = FALSE)
 
  
 # dataModRange
})()
```



```{r}



approxLinFunByUnitLen <- function(x,y) {
    ds <- sqrt(diff(x)^2 + diff(y)^2)
    s <- c(0, cumsum(ds))
    xByLength <- approxfun(s, x)
    yByLength <- approxfun(s, y)
    totalLength <- s[length(s)]
    
    xByUnitLength <- function(s) xByLength(s*totalLength)
    yByUnitLength <- function(s) yByLength(s*totalLength)
    
    
    function(s, ds = 0.1) {
      x <- xByUnitLength(s)
      y <- yByUnitLength(s)
      rotRad <- atan((yByUnitLength(s+ds) - y)/(xByUnitLength(s+ds) - x))
      
      list(x=x, y=y, rotRad = rotRad, srt = rotRad * 360 / 2 / pi)
    } 
  }

fun <- approxLinFunByUnitLen(1:10, (1:10)^2)

fun(0.4)

c(1,2,3) + 1

seq.int(from = 1, to = 16, length.out = 10) %>% round

diff((1:10)^2, differences = 2)
diff((1:10), lag = 2)
```




```{r}
## More examples in  demo(persp) !!
##                   -----------

# (1) The Obligatory Mathematical surface.
#     Rotated sinc function.

x <- seq(-10, 10, length= 30)
y <- x
f <- function(x, y) { r <- sqrt(x^2+y^2); 10 * sin(r)/r }
z <- outer(x, y, f)
z[is.na(z)] <- 1
op <- par(bg = "white")
persp(x, y, z, theta = 30, phi = 30, expand = 0.5, col = "lightblue")
persp(x, y, z, theta = 30, phi = 30, expand = 0.5, col = "lightblue",
      ltheta = 120, shade = 0.75, ticktype = "detailed",
      xlab = "X", ylab = "Y", zlab = "Sinc( r )"
) -> res
round(res, 3)

# (2) Add to existing persp plot - using trans3d() :

xE <- c(-10,10); xy <- expand.grid(xE, xE)
points(trans3d(xy[,1], xy[,2], 6, pmat = res), col = 2, pch = 16)
lines (trans3d(x, y = 10, z = 6 + sin(x), pmat = res), col = 3)

phi <- seq(0, 2*pi, len = 201)
r1 <- 7.725 # radius of 2nd maximum
xr <- r1 * cos(phi)
yr <- r1 * sin(phi)
lines(trans3d(xr,yr, f(xr,yr), res), col = "pink", lwd = 2)
## (no hidden lines)

# (3) Visualizing a simple DEM model

z <- 2 * volcano        # Exaggerate the relief
x <- 10 * (1:nrow(z))   # 10 meter spacing (S to N)
y <- 10 * (1:ncol(z))   # 10 meter spacing (E to W)
## Don't draw the grid lines :  border = NA
par(bg = "slategray")
persp(x, y, z, theta = 135, phi = 30, col = "green3", scale = FALSE,
      ltheta = -120, shade = 0.75, border = NA, box = FALSE)

# (4) Surface colours corresponding to z-values

par(bg = "white")
x <- seq(-1.95, 1.95, length = 30)
y <- seq(-1.95, 1.95, length = 35)
z <- outer(x, y, function(a, b) a*b^2)
nrz <- nrow(z)
ncz <- ncol(z)
# Create a function interpolating colors in the range of specified colors
jet.colors <- colorRampPalette( c("blue", "green") )
# Generate the desired number of colors from this palette
nbcol <- 100
color <- jet.colors(nbcol)
# Compute the z-value at the facet centres
zfacet <- z[-1, -1] + z[-1, -ncz] + z[-nrz, -1] + z[-nrz, -ncz]
# Recode facet z-values into color indices
facetcol <- cut(zfacet, nbcol)
persp(x, y, z, col = color[facetcol], phi = 30, theta = -30)

par(op)
```





```{r}
contourLines()


```



























